name: Clone Docker Image to GHCR
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  clone-image:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Pull, tag, and push image
      run: |
        docker pull ghcr.io/uncleluogithub/mous:latest
        docker tag ghcr.io/uncleluogithub/mous:latest ghcr.io/${{ github.repository }}/mous:latest
        docker push ghcr.io/${{ github.repository }}/mous:latest
